# Generated by Django 3.0.8 on 2020-08-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='created_at',
            new_name='cadastro_em',
        ),
        migrations.AddField(
            model_name='perfil',
            name='utlimo_acesso',
            field=models.DateField(auto_now=True),
        ),
    ]
