# Generated by Django 3.0.8 on 2020-08-03 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200803_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
