# Generated by Django 3.0.8 on 2020-08-03 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0003_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('ddd', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=11)),
                ('ddd_whatsapp', models.CharField(max_length=2)),
                ('whatsapp', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('newsletter', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo'), ('B', 'Bloqueado')], default='A', max_length=1)),
                ('motivo_bloqueio', models.TextField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
