# Generated by Django 3.0.8 on 2020-08-03 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0004_endereco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereco',
            new_name='Perfil',
        ),
    ]
