# Generated by Django 3.0.8 on 2020-08-03 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20200803_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
    ]
