# Generated by Django 3.0.8 on 2020-08-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='comentario',
        ),
    ]
