# Generated by Django 3.0.8 on 2020-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_remove_pedido_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comentario',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
